from PyQt5 import QtCore, QtWidgets

class Ui_Validation(object):
    # validation Check
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(447, 136)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 20, 81, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(315, 20, 71, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_1 = QtWidgets.QPushButton(Form)
        self.pushButton_1.setGeometry(QtCore.QRect(235, 20, 76, 23))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_0 = QtWidgets.QPushButton(Form)
        self.pushButton_0.setGeometry(QtCore.QRect(155, 20, 76, 23))
        self.pushButton_0.setObjectName("pushButton_0")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(30, 20, 125, 21))
        self.label_8.setObjectName("label_8")
        self.listWidget_8 = QtWidgets.QListWidget(Form)
        self.listWidget_8.setGeometry(QtCore.QRect(20, 50, 450, 125))
        self.listWidget_8.setObjectName("listView_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setStyleSheet('font-family : Arial')
        self.pushButton_3.setText(_translate("Form", "Val Start"))
        self.pushButton_3.setStyleSheet('background:White')
        self.pushButton_2.setText(_translate("Form", "Val Config"))
        self.pushButton_1.setText(_translate("Form", "Load Weight"))
        self.pushButton_0.setText(_translate("Form", "Load Image"))
        self.label_8.setText(_translate("Form", "Validation Ready"))

class Ui_Val(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(341, 364)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(80, 320, 171, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 61, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 115, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 91, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 91, 21))
        self.label_5.setObjectName("label_5")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(20, 210, 90, 21))
        self.textEdit.setObjectName("textEdit")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 280, 91, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(210, 60, 91, 21))
        self.label_7.setObjectName("label_7")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(180, 20, 61, 21))
        self.checkBox.setObjectName("radioButton")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(250, 20, 61, 21))
        self.checkBox_2.setObjectName("radioButton_2")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(220, 100, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(250, 140, 81, 21))
        self.checkBox_3.setObjectName("radioButton_3")
        self.checkBox_4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4.setGeometry(QtCore.QRect(160, 140, 81, 21))
        self.checkBox_4.setObjectName("radioButton_4")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(150, 180, 181, 71))
        self.listWidget.setObjectName("listWidget")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(210, 280, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(113, 198, 36, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(113, 222, 36, 21))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        Dialog.setStyleSheet('font-family : Arial')
        self.label.setText(_translate("Dialog", "USE"))
        self.label_2.setText(_translate("Dialog", "MODE"))
        self.label_3.setText(_translate("Dialog", "Detection Rate (%)"))
        self.label_4.setText(_translate("Dialog", "Backbone"))
        self.label_5.setText(_translate("Dialog", "Class Label"))
        self.label_6.setText(_translate("Dialog", "Color Splash"))
        self.label_7.setText(_translate("Dialog", "\'Inference\'"))
        self.checkBox.setText(_translate("Dialog", "CPU"))
        self.checkBox_2.setText(_translate("Dialog", "GPU"))
        self.checkBox_3.setText(_translate("Dialog", "Resnet 101"))
        self.checkBox_4.setText(_translate("Dialog", "Resnet 50"))
        self.pushButton.setText(_translate("Dialog", "ON"))
        self.pushButton_2.setText(_translate("Dialog", "Add"))
        self.pushButton_3.setText(_translate("Dialog", "Del"))

class Ui_Show_All(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1030, 684)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 1011, 662))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "View Loss"))
        Dialog.setStyleSheet('font-family : Arial')
        Dialog.setStyleSheet('color:Blue; background:Yellow')
        # self.textBrowser.setText(_translate("Dialog", "TRAINING LOSS"))

class Ui_Show(object):
    # validation Check
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(447, 136)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(440, 21, 80, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 21, 86, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(255, 21, 91, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(440, 0, 80, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(255, 0, 91, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(350, 0, 86, 20))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 20, 88, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 20, 45, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 0, 120, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 218, 100, 19))
        self.label_4.setObjectName("label_4")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(20, 50, 500, 165))
        self.listWidget.setObjectName("listView")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setStyleSheet('font-family : Arial')
        self.pushButton.setText(_translate("Form", "Show All"))
        self.pushButton_2.setText(_translate("Form", "Mode Change"))
        self.pushButton_3.setText(_translate("Form", "Stop Training"))
        self.pushButton_4.setText(_translate("Form", "Clear"))
        self.pushButton_4.setStyleSheet('color:White; background:Black')
        self.pushButton_5.setText(_translate("Form", "Cancel Stop"))
        self.pushButton_6.setText(_translate("Form", "Pause Train"))
        self.label.setText(_translate("Form", "Loss Show Box"))
        self.label.setStyleSheet('color:Blue; background:Yellow')

class Ui_Train(object):
    # training Check
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(448, 157)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 20, 81, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(305, 20, 81, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(220, 20, 81, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(30, 20, 181, 21))
        self.label_8.setObjectName("label_8")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(20, 50, 450, 91))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setStyleSheet('font-family : Arial')
        self.pushButton_3.setText(_translate("Form", "Train Start"))
        self.pushButton_3.setStyleSheet('background:White')
        self.pushButton_4.setText(_translate("Form", "Show Tensor"))
        self.pushButton_5.setText(_translate("Form", "close Tensor"))
        self.label_8.setText(_translate("Form", "Train Ready Box"))

class Ui_Json(object):
    # json file list
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(294, 190)
        self.listView_3 = QtWidgets.QListView(Form)
        self.listView_3.setGeometry(QtCore.QRect(10, 45, 261, 140))
        self.listView_3.setObjectName("listView_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.label_4.setObjectName("label_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(180, 10, 91, 21))
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setStyleSheet('font-family : Arial')
        self.label_4.setText(_translate("Form", "JSON File"))
        self.pushButton_5.setText(_translate("Form", "Import JSON"))

class Ui_Data(object):
    # image file list
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(295, 220)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(180, 20, 91, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.listView_2 = QtWidgets.QListView(Form)
        self.listView_2.setGeometry(QtCore.QRect(10, 50, 261, 151))
        self.listView_2.setObjectName("listView_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setStyleSheet('font-family : Arial')
        self.pushButton_4.setText(_translate("Form", "Import Image"))
        self.label_3.setText(_translate("Form", "Image File"))

class Ui_ConfigOpt(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(349, 440)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(80, 400, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 10, 131, 21))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(250, 100, 81, 21))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(260, 40, 71, 22))
        self.spinBox.setObjectName("spinBox")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 131, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 131, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 131, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 190, 131, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 131, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 220, 131, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(10, 130, 131, 21))
        self.label_8.setObjectName("label_8")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(170, 130, 81, 21))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(260, 130, 81, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(260, 160, 81, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4.setGeometry(QtCore.QRect(170, 160, 81, 21))
        self.checkBox_4.setObjectName("checkBox_4")
        self.spinBox_3 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_3.setGeometry(QtCore.QRect(280, 190, 42, 22))
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_4 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_4.setGeometry(QtCore.QRect(280, 220, 42, 22))
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(10, 250, 100, 21))
        self.label_11.setObjectName("label_11")
        self.spinBox_5 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_5.setGeometry(QtCore.QRect(260, 250, 62, 22))
        self.spinBox_5.setObjectName("spinBox_5")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(250, 70, 81, 21))
        self.listWidget.setObjectName("listView")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(10, 280, 131, 21))
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(280, 280, 35, 21))
        self.pushButton.setObjectName("pushButton")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(10, 310, 100, 21))
        self.label_10.setObjectName("label_10")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(260, 310, 65, 22))
        self.comboBox.setObjectName("comboBox")

        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(10, 340, 110, 21))
        self.label_12.setObjectName("label_12")
        self.horizontalSlider_2 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(125, 340, 200, 30))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setRange(20, 100)  # 범위 (min, max)
        self.horizontalSlider_2.setValue(90)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.listWidget_2 = QtWidgets.QListWidget(Dialog)
        self.listWidget_2.setGeometry(QtCore.QRect(135, 375, 170, 21))
        self.listWidget_2.setObjectName("listView")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        Dialog.setStyleSheet('Font-family : Arial')
        self.label.setText(_translate("Dialog", "Configuration Option"))
        self.label_2.setText(_translate("Dialog", "Epoch"))
        self.label_3.setText(_translate("Dialog", "Batch Size"))
        self.label_4.setText(_translate("Dialog", "Learning Rate"))
        self.label_5.setText(_translate("Dialog", "GPU COUNT"))
        self.label_6.setText(_translate("Dialog", "CPU / GPU"))
        self.label_7.setText(_translate("Dialog", "Images per GPU"))
        self.label_8.setText(_translate("Dialog", "BACKBONE"))
        self.label_9.setText(_translate("Dialog", "Mask opt"))
        self.label_10.setText(_translate("Dialog", "Layers"))
        self.label_11.setText(_translate("Dialog", "Steps per Ep"))
        self.label_12.setText(_translate("Dialog", "Train/Val Ratio"))
        self.checkBox.setText(_translate("Dialog", "Resnet50"))
        self.checkBox_2.setText(_translate("Dialog", "Resnet101"))
        self.checkBox_3.setText(_translate("Dialog", "GPU"))
        self.checkBox_4.setText(_translate("Dialog", "CPU"))
        self.pushButton.setText(_translate("Dialog", "On"))

class Ui_ConfigList(object):
    # config _list
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(200, 281)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.listWidget_5 = QtWidgets.QListWidget(Form)
        self.listWidget_5.setGeometry(QtCore.QRect(10, 40, 210, 240))
        self.listWidget_5.setObjectName("listView_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setStyleSheet('font-family: Arial')
        self.pushButton.setText(_translate("Form", "Config"))

class Ui_Config(object):
    # fast config ctrl
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(230, 150)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.label_5.setObjectName("label_5")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(150, 20, 71, 22))
        self.spinBox.setObjectName("spinBox")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 80, 21))
        self.label_7.setObjectName("label_7")
        self.spinBox_2 = QtWidgets.QSpinBox(Form)
        self.spinBox_2.setGeometry(QtCore.QRect(150, 50, 71, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(Form)
        self.spinBox_3.setGeometry(QtCore.QRect(150, 80, 71, 22))
        self.spinBox_3.setObjectName("spinBox_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 110, 81, 21))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(140, 110, 81, 21))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setStyleSheet('font-family : Arial')
        self.label_5.setText(_translate("Form", "Epoch"))
        self.label_6.setText(_translate("Form", "GPU Count"))
        self.label_7.setText(_translate("Form", "Img per GPU"))
        self.label.setText(_translate("Form", "Learning Rate"))

class Ui_Class(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(280, 180)
        # self.pushButton_1 = QtWidgets.QPushButton(Form)
        # self.pushButton_1.setGeometry(QtCore.QRect(190, 50, 81, 23))
        # self.pushButton_1.setObjectName("pushButton_6")
        # self.pushButton_2 = QtWidgets.QPushButton(Form)
        # self.pushButton_2.setGeometry(QtCore.QRect(190, 20, 81, 23))
        # self.pushButton_2.setObjectName("pushButton_2")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(10, 50, 261, 145))
        self.listWidget.setObjectName("listWidget")
        # self.label = QtWidgets.QLabel(Form)
        # self.label.setGeometry(QtCore.QRect(10, 40, 51, 31))
        # self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.label_2.setObjectName("label_2")
        # self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        # self.lineEdit_2.setGeometry(QtCore.QRect(50, 40, 131, 31))
        # self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setStyleSheet('font-family : Arial')
        # self.pushButton_1.setText(_translate("Form", "Add"))
        # self.pushButton_2.setText(_translate("Form", "Del"))
        # self.label.setText(_translate("Form", "Put in"))
        self.label_2.setText(_translate("Form", "Attribute Class"))